HTTP/1.1 403 Forbidden
Date: Thu, 07 Mar 2019 09:03:43 GMT
Server: Apache
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json;charset=ISO-8859-1

{"error":{"code":403,"message":"Forbidden","requested URI":"\/checkout\/\/v41\/payments\/"}}"
